---
name: main

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    strategy:
      matrix:
        node:
          - '14'
          - '16'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup
        with:
          node_version: ${{ matrix.node }}
      - name: Test
        run: npm test
  lint:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    strategy:
      matrix:
        node:
          - '14'
          - '16'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup
        with:
          node_version: ${{ matrix.node }}
      - name: Lint
        run: npm run lint
